### ISSUE TITLE
Fix missing functions/methods

### ISSUE THREAD

**Issue by yogeshrnaik** [servirtium/servirtium-python#5]
The https://github.com/servirtium/demo-python-climate-tck contains following errors due to missing functions/methods in https://github.com/servirtium/servirtium-python library
```
Cannot find reference 'set_markdown_files' in 'recorder.py' 
Unresolved attribute reference 'set_invoking_method' for class 'RecorderHttpHandler' 

Cannot find reference 'set_markdown_files' in 'playback.py' 
Unresolved attribute reference 'set_invoking_method' for class 'MockServiceHttpHandler' 
```

![image](https://user-images.githubusercontent.com/7280179/103152480-66d44100-47ae-11eb-8390-4ce4e4f8a729.png)

![Uploading image.png…]()

**Comment by paul-hammant** [comment]
Method names fixed.

**Comment by yogeshrnaik** [comment]
Fixed
https://github.com/servirtium/demo-python-climate-tck/commit/1e17f67f72affd9ed9ccae3fed59cbfde179d909
